# fly.toml file generated for bookstair on 2023-03-09T22:29:28+09:00

app = "bookstair"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
# processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.args]]
    command = "bundle exec sidekiq -c 5 -r ./config/environment.rb -e production"
    config = "config/sidekiq.yml"
    schedule = "config/schedule.yml"

[processes]
  web = "bin/rails fly:server"
  worker = "bundle exec sidekiq"