# fly.toml file generated for bookstair on 2023-03-09T22:29:28+09:00

app = "bookstair"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  name = "web"
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [services.http_checks]
    path = "/"
    interval = 10000
    timeout = 2000
    tls_skip_verify = false

[[services]]
  name = "worker"
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [services.args]
    command = "bundle exec sidekiq -c 5 -r ./config/environment.rb -e production"
    config = "config/sidekiq.yml"
    schedule = "config/schedule.yml"
