---
:concurrency: 25
:pidfile: ./tmp/pids/sidekiq.pid
:queues:
  - [critical, 4]
  - [default, 3]
  - [low, 2]
  - [mailers, 1]

:logfile: ./log/sidekiq.log
:timeout: 30
:verbose: false
:environment: development
:schedule: config/schedule.yml

:redis:
  url: Rails.application.credentials.redis[:url].to_s

:schedule:
  fetch_feeds:
  cron: '1 5,17 * * *'
  class: FetchFeedsJob

  # ジョブ2
  update_feeds:
    cron: '59 4 * * *'
    class: UpdateFeedsJob